version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
    command: cef run

  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "pip install -e .[dev] && pytest -v --cov=src --cov-report=term-missing"

  lint:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "pip install -e .[dev] && 
             flake8 src/ && 
             mypy src/ && 
             isort --check-only src/"

  format:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "pip install -e .[dev] && 
             black src/ tests/ examples/ && 
             isort src/ tests/ examples/"
